<?php

namespace Natue\Bundle\ZedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZedSupplierSkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZedSupplierSkuRepository extends EntityRepository
{
    public function findBySkuAndSupplier($sku, $supplier)
    {
        $query = $this->createQueryBuilder('zedSupplierSku')
            ->innerJoin(
                'NatueZedBundle:ZedProduct',
                'zedProduct',
                'WITH',
                'zedProduct.id = zedSupplierSku.zedProduct'
            )
            ->where('zedProduct.zedSupplier = :supplier')
            ->andWhere('zedSupplierSku.sku = :sku')
            ->setParameters(
                [
                    'sku' => $sku,
                    'supplier' => $supplier,
                ]
            )
            ->getQuery();

        return $query->getResult();
    }
}
