imports:
    - { resource: config.yml }
    - { resource: parameters_circleci.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

swiftmailer:
    disable_delivery: true
